^!0::RunNationalGeneralProspectFillFromClipboard()
^!9::RunNewProspectFillFromClipboard()
^!t::RunPasteLastConfiguredDatePreset()
^!y::RunPasteTomorrowPhonePreset()
^!k::RunCrmAttemptedContactWorkflow()
^!j::RunCrmQuoteCallWorkflow()
